import {
  Injectable,
  NotFoundException,
  ForbiddenException,
  BadRequestException,
  ConflictException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '@/prisma/prisma.service';
import { CreateStreamDto } from './dto/create-stream.dto';
import { UpdateStreamDto } from './dto/update-stream.dto';
import { SendGiftDto } from './dto/send-gift.dto';
import { PaginationQueryDto } from './dto/pagination-query.dto';
import { GiftLeaderboardEntry } from './interfaces/live-stream.interface';
import { OnModuleInit } from '@nestjs/common';

@Injectable()
export class LiveStreamService implements OnModuleInit {
  private readonly logger = new Logger(LiveStreamService.name);

  constructor(private readonly prisma: PrismaService) {}

  async onModuleInit() {
    try {
      this.logger.log('Checking for is_ingesting column...');
      await this.prisma.$executeRawUnsafe(`
        ALTER TABLE live_streams 
        ADD COLUMN IF NOT EXISTS is_ingesting BOOLEAN DEFAULT false;
      `);
    } catch (error) {
      this.logger.error('Failed to add is_ingesting column:', error);
    }
  }

  // ──────────────────────────────────────────────────────────
  // Stream CRUD
  // ──────────────────────────────────────────────────────────

  /**
   * Create (schedule) a new live stream.
   * Only users with a verified artist_account linked to the fandom's artist can create.
   */
  async createStream(userId: string, dto: CreateStreamDto) {
    // 1. Verify user has artist_account
    const artistAccount = await this.prisma.artist_accounts.findUnique({
      where: { user_id: userId },
    });
    if (!artistAccount) {
      throw new ForbiddenException(
        'Only artist accounts can create live streams',
      );
    }

    // 2. Verify fandom exists and belongs to the same artist (if provided)
    if (dto.fandom_id) {
      const fandom = await this.prisma.fandoms.findUnique({
        where: { fandom_id: dto.fandom_id },
      });
      if (!fandom) throw new NotFoundException('Fandom not found');

      // Artist must be the group artist or solo artist linked to this fandom
      if (artistAccount.artist_id !== fandom.artist_id) {
        throw new ForbiddenException('You can only stream in your own fandom');
      }
    }

    // 3. Prevent duplicate live/scheduled streams per artist/fandom
    const existingLive = await this.prisma.live_streams.findFirst({
      where: {
        host_user_id: userId,
        fandom_id: dto.fandom_id ?? null,
        status: { in: ['live', 'scheduled'] },
      },
    });
    if (existingLive) {
      throw new ConflictException(
        'There is already an active or scheduled stream for this account/fandom',
      );
    }

    // 4. Create stream — stream_key auto-generated by DB default
    const stream = await this.prisma.live_streams.create({
      data: {
        fandom_id: dto.fandom_id ?? null,
        host_user_id: userId,
        title: dto.title,
        description: dto.description ?? null,
        thumbnail_url: dto.thumbnail_url ?? null,
        is_portrait: dto.is_portrait ?? false,
        scheduled_at: dto.scheduled_at ? new Date(dto.scheduled_at) : null,
      },
    });

    // Build RTMP/HLS URLs from env
    const rtmpHost = process.env.SRS_RTMP_HOST;
    const httpHost = process.env.SRS_HTTP_HOST;
    
    if (rtmpHost && httpHost) {
      const rtmp_url = `rtmp://${rtmpHost}/live/${stream.stream_key}`;
      const hls_url = `https://${httpHost}/live/${stream.stream_key}.m3u8`;
      return this.prisma.live_streams.update({
        where: { stream_id: stream.stream_id },
        data: { rtmp_url, hls_url },
      });
    }

    return stream;
  }

  /** Update stream metadata (title, description, thumbnail, scheduled_at) */
  async updateStream(userId: string, streamId: string, dto: UpdateStreamDto) {
    const stream = await this.findStreamOrFail(streamId);
    this.assertIsHost(stream.host_user_id, userId);

    if (stream.status === 'ended' || stream.status === 'cancelled') {
      throw new BadRequestException('Cannot edit a finished stream');
    }

    return this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: {
        ...(dto.title && { title: dto.title }),
        ...(dto.description !== undefined && { description: dto.description }),
        ...(dto.thumbnail_url !== undefined && {
          thumbnail_url: dto.thumbnail_url,
        }),
        ...(dto.scheduled_at
          ? { scheduled_at: new Date(dto.scheduled_at) }
          : {}),
      },
    });
  }

  /** Go live — changes status from scheduled → live and sets started_at */
  async startStream(userId: string, streamId: string) {
    const stream = await this.findStreamOrFail(streamId);
    this.assertIsHost(stream.host_user_id, userId);

    if (stream.status !== 'scheduled') {
      throw new BadRequestException(
        `Cannot start a stream with status "${stream.status}"`,
      );
    }

    return this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: { status: 'live', started_at: new Date() },
    });
  }

  /** End a live stream */
  async endStream(userId: string, streamId: string) {
    const stream = await this.findStreamOrFail(streamId);
    this.assertIsHost(stream.host_user_id, userId);

    if (stream.status !== 'live') {
      throw new BadRequestException('Stream is not currently live');
    }

    return this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: { status: 'ended', ended_at: new Date(), is_ingesting: false },
    });
  }

  /** Cancel a scheduled stream */
  async cancelStream(userId: string, streamId: string) {
    const stream = await this.findStreamOrFail(streamId);
    this.assertIsHost(stream.host_user_id, userId);

    if (stream.status === 'live') {
      throw new BadRequestException(
        'Cannot cancel a live stream. End it instead.',
      );
    }
    if (stream.status === 'ended' || stream.status === 'cancelled') {
      throw new BadRequestException('Stream is already finished');
    }

    return this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: { status: 'cancelled', is_ingesting: false },
    });
  }

  // ──────────────────────────────────────────────────────────
  // Query
  // ──────────────────────────────────────────────────────────

  /** List live + scheduled streams (global feed, newest first) */
  async listStreams(query: PaginationQueryDto) {
    const { page = 1, limit = 20 } = query;
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.live_streams.findMany({
        where: { status: 'live' },
        include: {
          host: {
            select: {
              user_id: true,
              fullname: true,
              image_url: true,
              role: true,
              artist_account: {
                include: {
                  artist: true,
                  member: true
                }
              }
            },
          },
          fandom: {
            select: {
              fandom_id: true,
              name: true,
              slug: true,
              image_url: true,
            },
          },
        },
        orderBy: [
          { status: 'asc' },
          { started_at: 'desc' },
          { scheduled_at: 'asc' },
        ],
        skip,
        take: limit,
      }),
      this.prisma.live_streams.count({
        where: { status: 'live' },
      }),
    ]);

    return {
      data: items,
      meta: { page, limit, total, total_pages: Math.ceil(total / limit) },
    };
  }

  /** List my own streams (Artist only) */
  async listMyStreams(userId: string, query: PaginationQueryDto) {
    const { page = 1, limit = 20 } = query;
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.live_streams.findMany({
        where: { 
          host_user_id: userId,
          status: { in: ['live', 'scheduled'] } 
        },
        include: {
          host: {
            select: {
              user_id: true,
              fullname: true,
              image_url: true,
              role: true,
              artist_account: {
                include: {
                  artist: true,
                  member: true
                }
              }
            },
          },
          fandom: {
            select: {
              fandom_id: true,
              name: true,
              slug: true,
              image_url: true,
            },
          },
        },
        orderBy: { created_at: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.live_streams.count({
        where: { 
          host_user_id: userId,
          status: { in: ['live', 'scheduled'] } 
        },
      }),
    ]);

    return {
      data: items,
      meta: { page, limit, total, total_pages: Math.ceil(total / limit) },
    };
  }

  /** List streams for a specific fandom */
  async listFandomStreams(fandomId: string, query: PaginationQueryDto) {
    const { page = 1, limit = 20 } = query;
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.live_streams.findMany({
        where: { fandom_id: fandomId },
        include: {
          host: { select: { user_id: true, fullname: true } },
        },
        orderBy: { created_at: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.live_streams.count({ where: { fandom_id: fandomId } }),
    ]);

    return {
      data: items,
      meta: { page, limit, total, total_pages: Math.ceil(total / limit) },
    };
  }

  /** Get single stream detail */
  async getStream(streamId: string) {
    return this.findStreamOrFail(streamId, {
      host: {
        select: {
          user_id: true,
          fullname: true,
          image_url: true,
          role: true,
          artist_account: {
            include: {
              artist: true,
              member: true
            }
          }
        }
      },
      fandom: {
        select: { fandom_id: true, name: true, slug: true, image_url: true },
      },
    });
  }

  // ──────────────────────────────────────────────────────────
  // Viewer tracking (called by WebSocket gateway)
  // ──────────────────────────────────────────────────────────

  async joinStream(streamId: string, userId: string): Promise<number> {
    const stream = await this.findStreamOrFail(streamId);
    if (stream.status !== 'live') {
      return 0; // Allow joining for preview, but don't track viewers yet
    }

    await this.prisma.stream_viewers.upsert({
      where: { stream_id_user_id: { stream_id: streamId, user_id: userId } },
      create: { stream_id: streamId, user_id: userId },
      update: { joined_at: new Date(), left_at: null },
    });

    const updated = await this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: {
        viewer_count: { increment: 1 },
      },
      select: { viewer_count: true, peak_viewer_count: true },
    });

    // Update peak if needed
    if (updated.viewer_count > updated.peak_viewer_count) {
      await this.prisma.live_streams.update({
        where: { stream_id: streamId },
        data: { peak_viewer_count: updated.viewer_count },
      });
    }

    return updated.viewer_count;
  }

  async leaveStream(streamId: string, userId: string): Promise<number> {
    await this.prisma.stream_viewers.updateMany({
      where: { stream_id: streamId, user_id: userId, left_at: null },
      data: { left_at: new Date() },
    });

    const updated = await this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: { viewer_count: { decrement: 1 } },
      select: { viewer_count: true },
    });

    // Clamp to 0
    if (updated.viewer_count < 0) {
      await this.prisma.live_streams.update({
        where: { stream_id: streamId },
        data: { viewer_count: 0 },
      });
      return 0;
    }

    return updated.viewer_count;
  }

  // ──────────────────────────────────────────────────────────
  // Chat Messages
  // ──────────────────────────────────────────────────────────

  async sendMessage(streamId: string, userId: string, content: string) {
    const stream = await this.findStreamOrFail(streamId);
    if (stream.status !== 'live') {
      throw new BadRequestException('Stream is not live');
    }

    return this.prisma.stream_messages.create({
      data: { stream_id: streamId, user_id: userId, content },
      include: {
        user: {
          select: {
            user_id: true,
            fullname: true,
            image_url: true,
            role: true,
            artist_account: {
              include: {
                artist: true,
                member: true,
              },
            },
          },
        },
      },
    });
  }

  async getMessages(streamId: string, query: PaginationQueryDto) {
    await this.findStreamOrFail(streamId);
    const { page = 1, limit = 50 } = query;
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.stream_messages.findMany({
        where: { stream_id: streamId, is_deleted: false },
        include: {
          user: {
            select: {
              user_id: true,
              fullname: true,
              image_url: true,
              role: true,
              artist_account: {
                include: {
                  artist: true,
                  member: true,
                },
              },
            },
          },
        },
        orderBy: { created_at: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.stream_messages.count({
        where: { stream_id: streamId, is_deleted: false },
      }),
    ]);

    return {
      data: items.reverse(),
      meta: { page, limit, total, total_pages: Math.ceil(total / limit) },
    };
  }

  // ──────────────────────────────────────────────────────────
  // Gifts
  // ──────────────────────────────────────────────────────────

  async sendGift(streamId: string, senderId: string, dto: SendGiftDto) {
    const stream = await this.findStreamOrFail(streamId);
    if (stream.status !== 'live') {
      throw new BadRequestException('Stream is not live');
    }

    const giftType = await this.prisma.gift_types.findFirst({
      where: { id: dto.gift_type_id, is_active: true },
    });
    if (!giftType) throw new NotFoundException('Gift type not found');

    const totalCoins = giftType.coin_value * dto.quantity;

    // Atomically deduct coins and create gift record
    const gift = await this.prisma.$transaction(async (tx) => {
      // Check & deduct coins
      const user = await tx.users.findUnique({
        where: { user_id: senderId },
        select: { coins: true, bonus_coins: true },
      });
      if (!user) throw new NotFoundException('User not found');

      const totalBalance = user.coins + user.bonus_coins;
      if (totalBalance < totalCoins) {
        throw new BadRequestException(
          `Insufficient coins. Need ${totalCoins}, have ${totalBalance}`,
        );
      }

      // Deduct — use bonus coins first, then regular
      let remainingToDeduct = totalCoins;
      let bonusDeduction = 0;
      let regularDeduction = 0;

      if (user.bonus_coins >= remainingToDeduct) {
        bonusDeduction = remainingToDeduct;
      } else {
        bonusDeduction = user.bonus_coins;
        remainingToDeduct -= user.bonus_coins;
        regularDeduction = remainingToDeduct;
      }

      const updatedUser = await tx.users.update({
        where: { user_id: senderId },
        data: {
          coins: { decrement: regularDeduction },
          bonus_coins: { decrement: bonusDeduction },
        },
      });

      // Log transaction
      await tx.coin_transactions.create({
        data: {
          user_id: senderId,
          type: 'spend',
          amount: regularDeduction,
          bonus_amount: bonusDeduction,
          balance_after: updatedUser.coins,
          bonus_balance_after: updatedUser.bonus_coins,
          note: `Gift: ${dto.quantity}x ${giftType.display_name} in stream`,
          ref_id: streamId,
        },
      });

      // Create gift record
      const newGift = await tx.stream_gifts.create({
        data: {
          stream_id: streamId,
          sender_id: senderId,
          gift_type_id: dto.gift_type_id,
          quantity: dto.quantity,
          total_coins: totalCoins,
        },
        include: {
          sender: { select: { user_id: true, fullname: true } },
          gift_type: {
            select: {
              id: true,
              name: true,
              display_name: true,
              icon_url: true,
              coin_value: true,
            },
          },
        },
      });

      // Update stream totals
      await tx.live_streams.update({
        where: { stream_id: streamId },
        data: { total_gifts_coins: { increment: totalCoins } },
      });

      return newGift;
    });

    return gift;
  }

  async getGifts(streamId: string, query: PaginationQueryDto) {
    await this.findStreamOrFail(streamId);
    const { page = 1, limit = 50 } = query;
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.stream_gifts.findMany({
        where: { stream_id: streamId },
        include: {
          sender: {
            select: {
              user_id: true,
              fullname: true,
              image_url: true,
            },
          },
          gift_type: {
            select: {
              id: true,
              name: true,
              display_name: true,
              icon_url: true,
              coin_value: true,
            },
          },
        },
        orderBy: { created_at: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.stream_gifts.count({
        where: { stream_id: streamId },
      }),
    ]);

    return {
      data: items,
      meta: { page, limit, total, total_pages: Math.ceil(total / limit) },
    };
  }

  async getGiftLeaderboard(streamId: string): Promise<GiftLeaderboardEntry[]> {
    await this.findStreamOrFail(streamId);

    const results = await this.prisma.stream_gifts.groupBy({
      by: ['sender_id'],
      where: { stream_id: streamId },
      _sum: { total_coins: true },
      _count: { gift_id: true },
      orderBy: { _sum: { total_coins: 'desc' } },
      take: 20,
    });

    const userIds = results.map((r) => r.sender_id);
    const users = await this.prisma.users.findMany({
      where: { user_id: { in: userIds } },
      select: { user_id: true, fullname: true, image_url: true },
    });
    const userMap = new Map(users.map((u) => [u.user_id, { fullname: u.fullname, image_url: u.image_url }]));

    return results.map((r) => {
      const u = userMap.get(r.sender_id);
      return {
        sender_id: r.sender_id,
        fullname: u?.fullname ?? null,
        image_url: u?.image_url ?? null,
        total_coins: r._sum.total_coins ?? 0,
        gift_count: r._count.gift_id,
      };
    });
  }

  // ──────────────────────────────────────────────────────────
  // Gift Types (catalog)
  // ──────────────────────────────────────────────────────────

  async getGiftTypes() {
    return this.prisma.gift_types.findMany({
      where: { is_active: true },
      orderBy: { sort_order: 'asc' },
    });
  }

  async createGiftType(data: {
    name: string;
    display_name: string;
    icon_url?: string;
    coin_value: number;
    sort_order?: number;
  }) {
    return this.prisma.gift_types.create({ data });
  }

  async updateGiftType(
    id: string,
    data: Partial<{
      name: string;
      display_name: string;
      icon_url: string;
      coin_value: number;
      sort_order: number;
      is_active: boolean;
    }>,
  ) {
    return this.prisma.gift_types.update({ where: { id }, data });
  }

  // ──────────────────────────────────────────────────────────
  // SRS Webhook Handlers
  // ──────────────────────────────────────────────────────────

  /**
   * Called by SRS when OBS starts pushing RTMP.
   * Validates stream_key and auto-transitions to 'live'.
   * Returns { code: 0 } to allow, non-zero to reject.
   */
  async handlePublish(streamKey: string, clientIp: string) {
    const stream = await this.prisma.live_streams.findUnique({
      where: { stream_key: streamKey },
    });

    if (!stream) {
      this.logger.warn(`Rejected unknown stream_key: ${streamKey} from ${clientIp}`);
      return { code: 1, message: 'Unknown stream key' };
    }

    if (stream.status === 'ended' || stream.status === 'cancelled') {
      this.logger.warn(`Rejected finished stream: ${stream.stream_id}`);
      return { code: 2, message: 'Stream is already finished' };
    }

    // NOTE: We no longer auto-transition to 'live' here.
    // Instead, we mark it as 'ingesting' so the artist can preview.
    await this.prisma.live_streams.update({
      where: { stream_id: stream.stream_id },
      data: { is_ingesting: true },
    });
    
    this.logger.log(`Stream ${stream.stream_id} connected (Ingesting preview data)`);
    return { code: 0 };
  }

  /**
   * Called by SRS when OBS disconnects.
   * Auto-ends the stream.
   */
  async handleUnpublish(streamKey: string) {
    const stream = await this.prisma.live_streams.findUnique({
      where: { stream_key: streamKey },
    });

    if (!stream || stream.status !== 'live') {
      return { code: 0 };
    }

    await this.prisma.live_streams.update({
      where: { stream_id: stream.stream_id },
      data: { status: 'ended', ended_at: new Date(), is_ingesting: false },
    });

    this.logger.log(`Stream ${stream.stream_id} ended (OBS disconnected)`);
    return { code: 0, stream_id: stream.stream_id };
  }

  /**
   * Called by the converter service when FLV → MP4 conversion is done.
   * Sets the replay_url so fans can watch the VOD.
   */
  async setReplayUrl(streamKey: string, replayUrl: string) {
    const stream = await this.prisma.live_streams.findUnique({
      where: { stream_key: streamKey },
    });

    if (!stream) {
      throw new NotFoundException(`No stream found for key: ${streamKey}`);
    }

    const updated = await this.prisma.live_streams.update({
      where: { stream_id: stream.stream_id },
      data: { replay_url: replayUrl },
    });

    this.logger.log(`Replay ready for stream ${stream.stream_id}: ${replayUrl}`);
    return updated;
  }

  // ──────────────────────────────────────────────────────────
  // Replay Queries
  // ──────────────────────────────────────────────────────────

  /** List ended streams that have a replay available */
  async listReplays(query: PaginationQueryDto) {
    const { page = 1, limit = 20 } = query;
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.live_streams.findMany({
        where: { status: 'ended', replay_url: { not: null } },
        include: {
          host: { select: { user_id: true, fullname: true } },
          fandom: {
            select: { fandom_id: true, name: true, slug: true, image_url: true },
          },
        },
        orderBy: { ended_at: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.live_streams.count({
        where: { status: 'ended', replay_url: { not: null } },
      }),
    ]);

    return {
      data: items,
      meta: { page, limit, total, total_pages: Math.ceil(total / limit) },
    };
  }

  /** List replays for a specific fandom */
  async listFandomReplays(fandomId: string, query: PaginationQueryDto) {
    const { page = 1, limit = 20 } = query;
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.live_streams.findMany({
        where: {
          fandom_id: fandomId,
          status: 'ended',
          replay_url: { not: null },
        },
        include: {
          host: { select: { user_id: true, fullname: true } },
        },
        orderBy: { ended_at: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.live_streams.count({
        where: {
          fandom_id: fandomId,
          status: 'ended',
          replay_url: { not: null },
        },
      }),
    ]);

    return {
      data: items,
      meta: { page, limit, total, total_pages: Math.ceil(total / limit) },
    };
  }

  // ──────────────────────────────────────────────────────────
  // Helpers
  // ──────────────────────────────────────────────────────────

  /** Look up a stream by its unique stream_key (used by SRS webhooks) */
  async getStreamByKey(streamKey: string) {
    return this.prisma.live_streams.findUnique({
      where: { stream_key: streamKey },
    });
  }


  private async findStreamOrFail(
    streamId: string,
    include?: Record<string, unknown>,
  ) {
    const stream = await this.prisma.live_streams.findUnique({
      where: { stream_id: streamId },
      ...(include ? { include } : {}),
    });
    if (!stream) throw new NotFoundException('Stream not found');
    return stream;
  }

  private assertIsHost(hostUserId: string, requestUserId: string) {
    if (hostUserId !== requestUserId) {
      throw new ForbiddenException(
        'Only the stream host can perform this action',
      );
    }
  }
}
