import {
  Injectable,
  NotFoundException,
  ForbiddenException,
  BadRequestException,
  ConflictException,
} from '@nestjs/common';
import { PrismaService } from '@/prisma/prisma.service';
import { CreateStreamDto } from './dto/create-stream.dto';
import { UpdateStreamDto } from './dto/update-stream.dto';
import { SendGiftDto } from './dto/send-gift.dto';
import { PaginationQueryDto } from './dto/pagination-query.dto';
import { GiftLeaderboardEntry } from './interfaces/live-stream.interface';

@Injectable()
export class LiveStreamService {
  constructor(private readonly prisma: PrismaService) {}

  // ──────────────────────────────────────────────────────────
  // Stream CRUD
  // ──────────────────────────────────────────────────────────

  /**
   * Create (schedule) a new live stream.
   * Only users with a verified artist_account linked to the fandom's artist can create.
   */
  async createStream(userId: string, dto: CreateStreamDto) {
    // 1. Verify user has artist_account
    const artistAccount = await this.prisma.artist_accounts.findUnique({
      where: { user_id: userId },
    });
    if (!artistAccount) {
      throw new ForbiddenException('Only artist accounts can create live streams');
    }

    // 2. Verify fandom exists and belongs to the same artist
    const fandom = await this.prisma.fandoms.findUnique({
      where: { fandom_id: dto.fandom_id },
    });
    if (!fandom) throw new NotFoundException('Fandom not found');

    // Artist must be the group artist or solo artist linked to this fandom
    if (artistAccount.artist_id !== fandom.artist_id) {
      throw new ForbiddenException('You can only stream in your own fandom');
    }

    // 3. Prevent duplicate live/scheduled streams per fandom
    const existingLive = await this.prisma.live_streams.findFirst({
      where: {
        fandom_id: dto.fandom_id,
        status: { in: ['live', 'scheduled'] },
      },
    });
    if (existingLive) {
      throw new ConflictException(
        'There is already an active or scheduled stream for this fandom',
      );
    }

    // 4. Create stream — stream_key auto-generated by DB default
    const stream = await this.prisma.live_streams.create({
      data: {
        fandom_id: dto.fandom_id,
        host_user_id: userId,
        title: dto.title,
        description: dto.description ?? null,
        thumbnail_url: dto.thumbnail_url ?? null,
        scheduled_at: dto.scheduled_at ? new Date(dto.scheduled_at) : null,
      },
    });

    // Build RTMP/HLS URLs from env, but only if SRS_HOST is configured
    const srsHost = process.env.SRS_HOST;
    if (srsHost) {
      const rtmp_url = `rtmp://${srsHost}/live/${stream.stream_key}`;
      const hls_url = `http://${srsHost}/live/${stream.stream_key}.m3u8`;
      return this.prisma.live_streams.update({
        where: { stream_id: stream.stream_id },
        data: { rtmp_url, hls_url },
      });
    }

    return stream;
  }

  /** Update stream metadata (title, description, thumbnail, scheduled_at) */
  async updateStream(userId: string, streamId: string, dto: UpdateStreamDto) {
    const stream = await this.findStreamOrFail(streamId);
    this.assertIsHost(stream.host_user_id, userId);

    if (stream.status === 'ended' || stream.status === 'cancelled') {
      throw new BadRequestException('Cannot edit a finished stream');
    }

    return this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: {
        ...(dto.title && { title: dto.title }),
        ...(dto.description !== undefined && { description: dto.description }),
        ...(dto.thumbnail_url !== undefined && { thumbnail_url: dto.thumbnail_url }),
        ...(dto.scheduled_at ? { scheduled_at: new Date(dto.scheduled_at) } : {}),
      },
    });
  }

  /** Go live — changes status from scheduled → live and sets started_at */
  async startStream(userId: string, streamId: string) {
    const stream = await this.findStreamOrFail(streamId);
    this.assertIsHost(stream.host_user_id, userId);

    if (stream.status !== 'scheduled') {
      throw new BadRequestException(
        `Cannot start a stream with status "${stream.status}"`,
      );
    }

    return this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: { status: 'live', started_at: new Date() },
    });
  }

  /** End a live stream */
  async endStream(userId: string, streamId: string) {
    const stream = await this.findStreamOrFail(streamId);
    this.assertIsHost(stream.host_user_id, userId);

    if (stream.status !== 'live') {
      throw new BadRequestException('Stream is not currently live');
    }

    return this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: { status: 'ended', ended_at: new Date() },
    });
  }

  /** Cancel a scheduled stream */
  async cancelStream(userId: string, streamId: string) {
    const stream = await this.findStreamOrFail(streamId);
    this.assertIsHost(stream.host_user_id, userId);

    if (stream.status === 'live') {
      throw new BadRequestException('Cannot cancel a live stream. End it instead.');
    }
    if (stream.status === 'ended' || stream.status === 'cancelled') {
      throw new BadRequestException('Stream is already finished');
    }

    return this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: { status: 'cancelled' },
    });
  }

  // ──────────────────────────────────────────────────────────
  // Query
  // ──────────────────────────────────────────────────────────

  /** List live + scheduled streams (global feed, newest first) */
  async listStreams(query: PaginationQueryDto) {
    const { page = 1, limit = 20 } = query;
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.live_streams.findMany({
        where: { status: { in: ['live', 'scheduled'] } },
        include: {
          host: { select: { user_id: true, fullname: true } },
          fandom: { select: { fandom_id: true, name: true, slug: true, image_url: true } },
        },
        orderBy: [{ status: 'asc' }, { started_at: 'desc' }, { scheduled_at: 'asc' }],
        skip,
        take: limit,
      }),
      this.prisma.live_streams.count({
        where: { status: { in: ['live', 'scheduled'] } },
      }),
    ]);

    return {
      data: items,
      meta: { page, limit, total, total_pages: Math.ceil(total / limit) },
    };
  }

  /** List streams for a specific fandom */
  async listFandomStreams(fandomId: string, query: PaginationQueryDto) {
    const { page = 1, limit = 20 } = query;
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.live_streams.findMany({
        where: { fandom_id: fandomId },
        include: {
          host: { select: { user_id: true, fullname: true } },
        },
        orderBy: { created_at: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.live_streams.count({ where: { fandom_id: fandomId } }),
    ]);

    return {
      data: items,
      meta: { page, limit, total, total_pages: Math.ceil(total / limit) },
    };
  }

  /** Get single stream detail */
  async getStream(streamId: string) {
    return this.findStreamOrFail(streamId, {
      host: { select: { user_id: true, fullname: true } },
      fandom: { select: { fandom_id: true, name: true, slug: true, image_url: true } },
    });
  }

  // ──────────────────────────────────────────────────────────
  // Viewer tracking (called by WebSocket gateway)
  // ──────────────────────────────────────────────────────────

  async joinStream(streamId: string, userId: string): Promise<number> {
    const stream = await this.findStreamOrFail(streamId);
    if (stream.status !== 'live') {
      throw new BadRequestException('Stream is not live');
    }

    await this.prisma.stream_viewers.upsert({
      where: { stream_id_user_id: { stream_id: streamId, user_id: userId } },
      create: { stream_id: streamId, user_id: userId },
      update: { joined_at: new Date(), left_at: null },
    });

    const updated = await this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: {
        viewer_count: { increment: 1 },
      },
      select: { viewer_count: true, peak_viewer_count: true },
    });

    // Update peak if needed
    if (updated.viewer_count > updated.peak_viewer_count) {
      await this.prisma.live_streams.update({
        where: { stream_id: streamId },
        data: { peak_viewer_count: updated.viewer_count },
      });
    }

    return updated.viewer_count;
  }

  async leaveStream(streamId: string, userId: string): Promise<number> {
    await this.prisma.stream_viewers.updateMany({
      where: { stream_id: streamId, user_id: userId, left_at: null },
      data: { left_at: new Date() },
    });

    const updated = await this.prisma.live_streams.update({
      where: { stream_id: streamId },
      data: { viewer_count: { decrement: 1 } },
      select: { viewer_count: true },
    });

    // Clamp to 0
    if (updated.viewer_count < 0) {
      await this.prisma.live_streams.update({
        where: { stream_id: streamId },
        data: { viewer_count: 0 },
      });
      return 0;
    }

    return updated.viewer_count;
  }

  // ──────────────────────────────────────────────────────────
  // Chat Messages
  // ──────────────────────────────────────────────────────────

  async sendMessage(streamId: string, userId: string, content: string) {
    const stream = await this.findStreamOrFail(streamId);
    if (stream.status !== 'live') {
      throw new BadRequestException('Stream is not live');
    }

    return this.prisma.stream_messages.create({
      data: { stream_id: streamId, user_id: userId, content },
      include: {
        user: { select: { user_id: true, fullname: true } },
      },
    });
  }

  async getMessages(streamId: string, query: PaginationQueryDto) {
    await this.findStreamOrFail(streamId);
    const { page = 1, limit = 50 } = query;
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.stream_messages.findMany({
        where: { stream_id: streamId, is_deleted: false },
        include: { user: { select: { user_id: true, fullname: true } } },
        orderBy: { created_at: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.stream_messages.count({
        where: { stream_id: streamId, is_deleted: false },
      }),
    ]);

    return {
      data: items.reverse(),
      meta: { page, limit, total, total_pages: Math.ceil(total / limit) },
    };
  }

  // ──────────────────────────────────────────────────────────
  // Gifts
  // ──────────────────────────────────────────────────────────

  async sendGift(streamId: string, senderId: string, dto: SendGiftDto) {
    const stream = await this.findStreamOrFail(streamId);
    if (stream.status !== 'live') {
      throw new BadRequestException('Stream is not live');
    }

    const giftType = await this.prisma.gift_types.findFirst({
      where: { id: dto.gift_type_id, is_active: true },
    });
    if (!giftType) throw new NotFoundException('Gift type not found');

    const totalCoins = giftType.coin_value * dto.quantity;

    // Atomically deduct coins and create gift record
    const gift = await this.prisma.$transaction(async (tx) => {
      // Check & deduct coins
      const user = await tx.users.findUnique({
        where: { user_id: senderId },
        select: { coins: true, bonus_coins: true },
      });
      if (!user) throw new NotFoundException('User not found');

      const totalBalance = user.coins + user.bonus_coins;
      if (totalBalance < totalCoins) {
        throw new BadRequestException(
          `Insufficient coins. Need ${totalCoins}, have ${totalBalance}`,
        );
      }

      // Deduct — use bonus coins first, then regular
      let remainingToDeduct = totalCoins;
      let bonusDeduction = 0;
      let regularDeduction = 0;

      if (user.bonus_coins >= remainingToDeduct) {
        bonusDeduction = remainingToDeduct;
      } else {
        bonusDeduction = user.bonus_coins;
        remainingToDeduct -= user.bonus_coins;
        regularDeduction = remainingToDeduct;
      }

      const updatedUser = await tx.users.update({
        where: { user_id: senderId },
        data: {
          coins: { decrement: regularDeduction },
          bonus_coins: { decrement: bonusDeduction },
        },
      });

      // Log transaction
      await tx.coin_transactions.create({
        data: {
          user_id: senderId,
          type: 'spend',
          amount: regularDeduction,
          bonus_amount: bonusDeduction,
          balance_after: updatedUser.coins,
          bonus_balance_after: updatedUser.bonus_coins,
          note: `Gift: ${dto.quantity}x ${giftType.display_name} in stream`,
          ref_id: streamId,
        },
      });

      // Create gift record
      const newGift = await tx.stream_gifts.create({
        data: {
          stream_id: streamId,
          sender_id: senderId,
          gift_type_id: dto.gift_type_id,
          quantity: dto.quantity,
          total_coins: totalCoins,
        },
        include: {
          sender: { select: { user_id: true, fullname: true } },
          gift_type: { select: { id: true, name: true, display_name: true, icon_url: true, coin_value: true } },
        },
      });

      // Update stream totals
      await tx.live_streams.update({
        where: { stream_id: streamId },
        data: { total_gifts_coins: { increment: totalCoins } },
      });

      return newGift;
    });

    return gift;
  }

  async getGiftLeaderboard(streamId: string): Promise<GiftLeaderboardEntry[]> {
    await this.findStreamOrFail(streamId);

    const results = await this.prisma.stream_gifts.groupBy({
      by: ['sender_id'],
      where: { stream_id: streamId },
      _sum: { total_coins: true },
      _count: { gift_id: true },
      orderBy: { _sum: { total_coins: 'desc' } },
      take: 20,
    });

    const userIds = results.map((r) => r.sender_id);
    const users = await this.prisma.users.findMany({
      where: { user_id: { in: userIds } },
      select: { user_id: true, fullname: true },
    });
    const userMap = new Map(users.map((u) => [u.user_id, u.fullname]));

    return results.map((r) => ({
      sender_id: r.sender_id,
      fullname: userMap.get(r.sender_id) ?? null,
      total_coins: r._sum.total_coins ?? 0,
      gift_count: r._count.gift_id,
    }));
  }

  // ──────────────────────────────────────────────────────────
  // Gift Types (catalog)
  // ──────────────────────────────────────────────────────────

  async getGiftTypes() {
    return this.prisma.gift_types.findMany({
      where: { is_active: true },
      orderBy: { sort_order: 'asc' },
    });
  }

  async createGiftType(data: {
    name: string;
    display_name: string;
    icon_url?: string;
    coin_value: number;
    sort_order?: number;
  }) {
    return this.prisma.gift_types.create({ data });
  }

  async updateGiftType(
    id: string,
    data: Partial<{
      name: string;
      display_name: string;
      icon_url: string;
      coin_value: number;
      sort_order: number;
      is_active: boolean;
    }>,
  ) {
    return this.prisma.gift_types.update({ where: { id }, data });
  }

  // ──────────────────────────────────────────────────────────
  // Helpers
  // ──────────────────────────────────────────────────────────

  private async findStreamOrFail(
    streamId: string,
    include?: Record<string, unknown>,
  ) {
    const stream = await this.prisma.live_streams.findUnique({
      where: { stream_id: streamId },
      ...(include ? { include } : {}),
    });
    if (!stream) throw new NotFoundException('Stream not found');
    return stream;
  }

  private assertIsHost(hostUserId: string, requestUserId: string) {
    if (hostUserId !== requestUserId) {
      throw new ForbiddenException('Only the stream host can perform this action');
    }
  }
}
